-- ============================================================
-- DOMINOVA OPERATING SYSTEM (DOMINOVA-OS)
-- SUPABASE POSTGRESQL CONSOLIDATED SCHEMA & SEED SCRIPT
-- ============================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- 2. CREATE TABLES
-- ============================================================

-- 2.1 USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'sales', 'manager', 'developer')),
  is_active INTEGER NOT NULL DEFAULT 1,
  avatar_url TEXT,
  phone TEXT,
  username TEXT UNIQUE,
  domain TEXT,
  employee_id TEXT,
  login_access INTEGER DEFAULT 1,
  joining_date TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);

-- 2.2 WALLETS TABLE
CREATE TABLE IF NOT EXISTS wallets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  total_earned NUMERIC NOT NULL DEFAULT 0,
  total_withdrawn NUMERIC NOT NULL DEFAULT 0,
  available_balance NUMERIC NOT NULL DEFAULT 0,
  pending_withdrawal NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wallets_user_id ON wallets(user_id);

-- 2.3 LEADS TABLE
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id TEXT NOT NULL UNIQUE,
  client_name TEXT NOT NULL,
  org_name TEXT,
  phone TEXT NOT NULL,
  email TEXT,
  google_business_url TEXT,
  instagram_url TEXT,
  other_url TEXT,
  lead_source TEXT DEFAULT 'Manual',
  assigned_to BIGINT REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'NEW'
    CHECK(status IN ('NEW','ASSIGNED','CONTACTED','INTERESTED','FOLLOW_UP','MANAGER_REVIEW','CONVERTED','LOST')),
  notes TEXT,
  requirements TEXT,
  quoted_amount NUMERIC,
  advance_amount NUMERIC DEFAULT 0,
  advance_received INTEGER NOT NULL DEFAULT 0,
  full_project_amount NUMERIC,
  next_followup_date TEXT,
  last_contacted_at TIMESTAMPTZ,
  project_confirmed INTEGER NOT NULL DEFAULT 0,
  project_confirmed_at TIMESTAMPTZ,
  project_confirmed_by BIGINT REFERENCES users(id),
  project_id BIGINT,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_lead_id ON leads(lead_id);
CREATE INDEX IF NOT EXISTS idx_leads_is_deleted ON leads(is_deleted);

-- 2.4 PROJECTS TABLE
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL UNIQUE,
  lead_id BIGINT REFERENCES leads(id),
  salesperson_id BIGINT NOT NULL REFERENCES users(id),
  developer_id BIGINT REFERENCES users(id),
  frontend_developer_id BIGINT REFERENCES users(id),
  backend_developer_id BIGINT REFERENCES users(id),
  hosting_developer_id BIGINT REFERENCES users(id),
  client_name TEXT NOT NULL,
  org_name TEXT,
  phone TEXT NOT NULL,
  email TEXT,
  google_business_url TEXT,
  instagram_url TEXT,
  other_url TEXT,
  requirements TEXT NOT NULL,
  specifications TEXT,
  website_expectations TEXT,
  full_project_amount NUMERIC NOT NULL,
  advance_amount NUMERIC NOT NULL DEFAULT 0,
  remaining_amount NUMERIC GENERATED ALWAYS AS (full_project_amount - advance_amount) STORED,
  developer_payout NUMERIC,
  backend_payout NUMERIC DEFAULT 0,
  hosting_payout NUMERIC DEFAULT 0,
  picked_components TEXT,
  sales_commission NUMERIC,
  final_website_url TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING_ADMIN_APPROVAL'
    CHECK(status IN (
      'PENDING_ADMIN_APPROVAL',
      'PENDING_FOUNDER_REVIEW',
      'PENDING_FOUNDER_ALLOCATION',
      'REJECTED_BY_ADMIN',
      'AVAILABLE_FOR_DEVELOPER',
      'AVAILABLE_FOR_DEVELOPERS',
      'ASSIGNED',
      'IN_DEVELOPMENT',
      'TESTING',
      'SUBMITTED',
      'PENDING_FINAL_APPROVAL',
      'REVISION_REQUIRED',
      'COMPLETED',
      'CLOSED'
    )),
  payment_status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK(payment_status IN ('PENDING','PARTIAL','PAID','CONFIRMED')),
  admin_approval_notes TEXT,
  rejection_reason TEXT,
  final_rejection_reason TEXT,
  salesperson_notes TEXT,
  revision_count INTEGER NOT NULL DEFAULT 0,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  approved_by BIGINT REFERENCES users(id),
  approved_at TIMESTAMPTZ,
  deadline TEXT
);

CREATE INDEX IF NOT EXISTS idx_projects_project_id ON projects(project_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_developer_id ON projects(developer_id);
CREATE INDEX IF NOT EXISTS idx_projects_salesperson_id ON projects(salesperson_id);
CREATE INDEX IF NOT EXISTS idx_projects_lead_id ON projects(lead_id);
CREATE INDEX IF NOT EXISTS idx_projects_is_deleted ON projects(is_deleted);

-- Add foreign key from leads(project_id) to projects(id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_leads_project'
  ) THEN
    ALTER TABLE leads ADD CONSTRAINT fk_leads_project FOREIGN KEY (project_id) REFERENCES projects(id);
  END IF;
END $$;

-- 2.5 LEAD FOLLOW-UPS
CREATE TABLE IF NOT EXISTS lead_followups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  created_by BIGINT NOT NULL REFERENCES users(id),
  followup_date TEXT NOT NULL,
  followup_time TEXT,
  reason TEXT NOT NULL,
  client_position TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK(status IN ('PENDING','DONE','MISSED')),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_followups_lead_id ON lead_followups(lead_id);
CREATE INDEX IF NOT EXISTS idx_followups_date ON lead_followups(followup_date);
CREATE INDEX IF NOT EXISTS idx_followups_created_by ON lead_followups(created_by);

-- 2.6 MANAGER ESCALATIONS
CREATE TABLE IF NOT EXISTS manager_escalations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  salesperson_id BIGINT NOT NULL REFERENCES users(id),
  manager_id BIGINT REFERENCES users(id),
  quoted_price NUMERIC,
  requirements TEXT,
  reason TEXT NOT NULL,
  salesperson_notes TEXT,
  manager_notes TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING_MANAGER'
    CHECK(status IN ('PENDING_MANAGER','IN_DISCUSSION','FOLLOW_UP','CONVERTED','LOST','CLOSED')),
  followup_date TEXT,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_escalations_lead_id ON manager_escalations(lead_id);
CREATE INDEX IF NOT EXISTS idx_escalations_manager_id ON manager_escalations(manager_id);
CREATE INDEX IF NOT EXISTS idx_escalations_salesperson_id ON manager_escalations(salesperson_id);
CREATE INDEX IF NOT EXISTS idx_escalations_is_deleted ON manager_escalations(is_deleted);

-- 2.7 PROJECT STATUS HISTORY
CREATE TABLE IF NOT EXISTS project_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  old_status TEXT,
  new_status TEXT NOT NULL,
  changed_by BIGINT NOT NULL REFERENCES users(id),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_psh_project_id ON project_status_history(project_id);

-- 2.8 PROJECT MESSAGES
CREATE TABLE IF NOT EXISTS project_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES users(id),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_messages_project_id ON project_messages(project_id);

-- 2.9 PROJECT FILES
CREATE TABLE IF NOT EXISTS project_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  uploaded_by BIGINT NOT NULL REFERENCES users(id),
  file_name TEXT NOT NULL,
  file_type TEXT,
  file_size BIGINT,
  file_path TEXT NOT NULL,
  description TEXT,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_files_project_id ON project_files(project_id);
CREATE INDEX IF NOT EXISTS idx_files_is_deleted ON project_files(is_deleted);

-- 2.10 PROJECT REVISIONS
CREATE TABLE IF NOT EXISTS project_revisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  revision_number INTEGER NOT NULL,
  rejection_reason TEXT NOT NULL,
  rejected_by BIGINT NOT NULL REFERENCES users(id),
  rejected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resubmitted_at TIMESTAMPTZ,
  resubmitted_url TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK(status IN ('PENDING','RESOLVED'))
);

CREATE INDEX IF NOT EXISTS idx_revisions_project_id ON project_revisions(project_id);

-- 2.11 WALLET TRANSACTIONS
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id TEXT NOT NULL UNIQUE,
  wallet_id BIGINT NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  project_id BIGINT REFERENCES projects(id),
  type TEXT NOT NULL
    CHECK(type IN (
      'DEVELOPER_EARNING',
      'SALES_COMMISSION',
      'WITHDRAWAL_DEBIT',
      'ADJUSTMENT_CREDIT',
      'ADJUSTMENT_DEBIT',
      'MANUAL_CREDIT'
    )),
  amount NUMERIC NOT NULL,
  direction TEXT NOT NULL CHECK(direction IN ('CREDIT','DEBIT')),
  description TEXT NOT NULL,
  note TEXT,
  status TEXT NOT NULL DEFAULT 'COMPLETED'
    CHECK(status IN ('PENDING','COMPLETED','REVERSED')),
  created_by BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wt_wallet_id ON wallet_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_wt_user_id ON wallet_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_wt_project_id ON wallet_transactions(project_id);

-- 2.12 WITHDRAWALS
CREATE TABLE IF NOT EXISTS withdrawals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  withdrawal_id TEXT NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  wallet_id BIGINT NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK(status IN ('PENDING','APPROVED','REJECTED','COMPLETED')),
  request_notes TEXT,
  admin_notes TEXT,
  reviewed_by BIGINT REFERENCES users(id),
  reviewed_at TIMESTAMPTZ,
  transaction_id BIGINT REFERENCES wallet_transactions(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_user_id ON withdrawals(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON withdrawals(status);

-- 2.13 NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'INFO'
    CHECK(type IN ('INFO','SUCCESS','WARNING','ERROR','ACTION_REQUIRED')),
  entity_type TEXT,
  entity_id BIGINT,
  link TEXT,
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);

-- 2.14 AUDIT LOGS
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id BIGINT,
  old_value TEXT,
  new_value TEXT,
  description TEXT NOT NULL,
  ip_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity_type, entity_id);

-- 2.15 LEAD ACTIVITIES
CREATE TABLE IF NOT EXISTS lead_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  activity_type TEXT NOT NULL,
  description TEXT NOT NULL,
  metadata TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_activities_lead_id ON lead_activities(lead_id);

-- 2.16 SETTINGS
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  description TEXT,
  updated_by BIGINT REFERENCES users(id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 3. PERMISSIONS & ROW LEVEL SECURITY (RLS)
-- ============================================================
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE lead_followups DISABLE ROW LEVEL SECURITY;
ALTER TABLE manager_escalations DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_status_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_revisions DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE withdrawals DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE lead_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;

GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- ============================================================
-- 4. SEED DATA
-- ============================================================

-- 4.1 USERS (9 columns)
INSERT INTO users (id, name, email, username, password_hash, role, phone, is_active, login_access) VALUES
  (1, 'Founder Admin', 'admin@dominova.in', 'admin', '$2a$10$0ksFVuE7F6/eGqXnHxd/ne0LHMUHJEBqgkNjbB3bs163yYzpcygA2', 'admin', '9000000001', 1, 1),
  (2, 'Rahul Sharma', 'sales1@dominova.in', 'sales1', '$2a$10$FeVLnxVshrhFXEzJLRyZAePm3ALQxFgMCHv2.JsVZyZJwlY3MXr16', 'sales', '9000000002', 1, 1),
  (3, 'Priya Patel', 'sales2@dominova.in', 'sales2', '$2a$10$FeVLnxVshrhFXEzJLRyZAePm3ALQxFgMCHv2.JsVZyZJwlY3MXr16', 'sales', '9000000003', 1, 1),
  (4, 'Arjun Singh', 'sales3@dominova.in', 'sales3', '$2a$10$FeVLnxVshrhFXEzJLRyZAePm3ALQxFgMCHv2.JsVZyZJwlY3MXr16', 'sales', '9000000004', 1, 1),
  (5, 'Meera Nair', 'manager@dominova.in', 'manager', '$2a$10$S1ljXhRIZBasnU/kNUenE.WPVE63L4bGjWqdv8O0p.rboXok8a8si', 'manager', '9000000005', 1, 1),
  (6, 'Vikram Dev', 'dev1@dominova.in', 'dev1', '$2a$10$14q8gsP/Bfio2vOzzpqyCuERK9WdLS.NmWtBImQiu1uSj80xoP46e', 'developer', '9000000006', 1, 1),
  (7, 'Sneha Reddy', 'dev2@dominova.in', 'dev2', '$2a$10$14q8gsP/Bfio2vOzzpqyCuERK9WdLS.NmWtBImQiu1uSj80xoP46e', 'developer', '9000000007', 1, 1),
  (8, 'Kiran Kumar', 'dev3@dominova.in', 'dev3', '$2a$10$14q8gsP/Bfio2vOzzpqyCuERK9WdLS.NmWtBImQiu1uSj80xoP46e', 'developer', '9000000008', 1, 1),
  (9, 'Aditya Verma', 'dev4@dominova.in', 'dev4', '$2a$10$14q8gsP/Bfio2vOzzpqyCuERK9WdLS.NmWtBImQiu1uSj80xoP46e', 'developer', '9000000009', 1, 1),
  (10, 'Deepika Joshi', 'dev5@dominova.in', 'dev5', '$2a$10$14q8gsP/Bfio2vOzzpqyCuERK9WdLS.NmWtBImQiu1uSj80xoP46e', 'developer', '9000000010', 1, 1)
ON CONFLICT (id) DO NOTHING;

-- 4.2 WALLETS (6 columns)
INSERT INTO wallets (id, user_id, total_earned, total_withdrawn, available_balance, pending_withdrawal) VALUES
  (1, 1, 0, 0, 0, 0),
  (2, 2, 2500, 0, 2500, 0),
  (3, 3, 0, 0, 0, 0),
  (4, 4, 0, 0, 0, 0),
  (5, 5, 0, 0, 0, 0),
  (6, 6, 0, 0, 0, 0),
  (7, 7, 0, 0, 0, 0),
  (8, 8, 0, 0, 0, 0),
  (9, 9, 5500, 0, 5500, 0),
  (10, 10, 0, 0, 0, 0)
ON CONFLICT (id) DO NOTHING;

-- 4.3 LEADS (19 columns)
INSERT INTO leads (
  id, lead_id, client_name, org_name, phone, email,
  google_business_url, instagram_url, lead_source, assigned_to,
  status, notes, requirements, quoted_amount, advance_amount,
  full_project_amount, next_followup_date, last_contacted_at, created_by
) VALUES
  (1, 'DOM-LEAD-0001', 'Suresh Gupta', 'Gupta Sweets', '9876543210', 'suresh@guptasweets.com', 'https://g.co/guptasweets', 'https://instagram.com/guptasweets', 'Instagram', NULL, 'NEW', 'Interested in a restaurant website', NULL, NULL, 0, NULL, NULL, NULL, 1),
  (2, 'DOM-LEAD-0002', 'Anita Mehta', 'Mehta Boutique', '9876543211', 'anita@mehtaboutique.in', 'https://g.co/mehtaboutique', 'https://instagram.com/mehtaboutique', 'Google', 2, 'ASSIGNED', 'Fashion boutique, wants e-commerce site', NULL, NULL, 0, NULL, NULL, NULL, 1),
  (3, 'DOM-LEAD-0003', 'Ramesh Pillai', 'Pillai Real Estate', '9876543212', 'ramesh@pillai.com', 'https://g.co/pillaiestates', NULL, 'Referral', 2, 'FOLLOW_UP', 'Called on 5th Sep. Client interested but wants to discuss after Diwali.', 'Property listing website with search filters and contact forms', 35000, 0, NULL, '2026-10-25', '2026-09-05 00:00:00+00', 1),
  (4, 'DOM-LEAD-0004', 'Kavitha Rao', 'Kavitha Beauty Salon', '9876543213', 'kavitha@beautysalon.in', NULL, 'https://instagram.com/kavithabeauty', 'Instagram', 3, 'INTERESTED', 'Very interested. Wants booking system integrated.', 'Salon booking website with appointment calendar', 25000, 0, NULL, NULL, '2026-09-08 00:00:00+00', 1),
  (5, 'DOM-LEAD-0005', 'Harish Agarwal', 'Agarwal Motors', '9876543214', 'harish@agarwalmotors.com', 'https://g.co/agarwalmotors', NULL, 'Google', 3, 'MANAGER_REVIEW', 'High value client. Needs founder to speak with.', 'Car dealership website with inventory management', 85000, 0, NULL, NULL, '2026-09-07 00:00:00+00', 1),
  (6, 'DOM-LEAD-0006', 'Pooja Iyer', 'Iyer Catering', '9876543215', 'pooja@iyercatering.com', 'https://g.co/iyercatering', 'https://instagram.com/iyercatering', 'Referral', 2, 'CONVERTED', NULL, 'Catering website with menu, gallery, and contact', 20000, 8000, 20000, NULL, '2026-09-01 00:00:00+00', 1),
  (7, 'DOM-LEAD-0007', 'Vijay Nair', 'Nair Travels', '9876543216', NULL, NULL, NULL, 'Cold Call', 4, 'LOST', 'Not interested, has own IT team.', NULL, NULL, 0, NULL, NULL, NULL, 1),
  (8, 'DOM-LEAD-0008', 'Sunita Krishnan', 'Krishnan Clinics', '9876543217', 'sunita@krish.clinic', 'https://g.co/krishnanclinic', NULL, 'Google', 4, 'CONTACTED', 'Doctor, wants appointment booking website', NULL, NULL, 0, NULL, NULL, '2026-09-09 00:00:00+00', 1)
ON CONFLICT (id) DO NOTHING;

-- 4.4 PROJECTS (27 columns)
INSERT INTO projects (
  id, project_id, lead_id, salesperson_id, developer_id,
  client_name, org_name, phone, email, google_business_url,
  instagram_url, requirements, specifications, website_expectations,
  full_project_amount, advance_amount, developer_payout, sales_commission,
  final_website_url, status, payment_status, salesperson_notes,
  final_rejection_reason, revision_count, completed_at, approved_by, approved_at
) VALUES
  (1, 'DOM-PROJ-0001', 6, 2, NULL, 'Pooja Iyer', 'Iyer Catering', '9876543215', 'pooja@iyercatering.com', 'https://g.co/iyercatering', 'https://instagram.com/iyercatering', 'Full catering website with menu showcase, gallery, testimonials, contact form and WhatsApp integration', 'Mobile-first design, fast loading, SEO optimized, CMS for menu updates', 'Professional, warm colors (orange/gold theme), easy to navigate', 20000, 8000, NULL, NULL, NULL, 'PENDING_ADMIN_APPROVAL', 'PARTIAL', 'Client very happy with our portfolio. Advance paid via UPI. Wants delivery in 3 weeks.', NULL, 0, NULL, NULL, NULL),
  (2, 'DOM-PROJ-0002', NULL, 3, NULL, 'Akhil Stores', 'Akhil General Stores', '9876543220', 'akhil@stores.com', 'https://g.co/akhilstores', NULL, 'E-commerce website for grocery store with cart, payment gateway and delivery tracking', 'WooCommerce style, Razorpay integration, UPI and card payment, WhatsApp order confirmation', 'Clean, modern grocery store theme. Must work perfectly on mobile.', 30000, 15000, 9000, NULL, NULL, 'AVAILABLE_FOR_DEVELOPER', 'PARTIAL', 'High-priority. Client wants launch before next month.', NULL, 0, NULL, NULL, NULL),
  (3, 'DOM-PROJ-0003', NULL, 2, 6, 'TechStart Solutions', 'TechStart Solutions Pvt Ltd', '9876543221', 'info@techstart.in', NULL, 'https://instagram.com/techstart_in', 'Corporate website with team page, services, portfolio, blog and contact form', 'React-based, fast loading, dark/light mode, AOS animations', 'Premium tech startup look. Dark theme with neon accents.', 25000, 12500, 7500, NULL, NULL, 'IN_DEVELOPMENT', 'PARTIAL', 'Tech-savvy client. Gave very detailed requirements.', NULL, 0, NULL, NULL, NULL),
  (4, 'DOM-PROJ-0004', NULL, 4, 7, 'Nisha Fashion House', 'Nisha Fashion', '9876543222', 'nisha@fashionhouse.com', 'https://g.co/nishafashion', 'https://instagram.com/nishafashion', 'Fashion e-commerce with size guide, lookbook, wishlist and checkout', 'Elegant feminine design, Instagram feed integration, fast image loading', 'Luxury fashion website feel. Pink and gold theme.', 35000, 20000, 10000, NULL, 'https://nisha-fashion-demo.netlify.app', 'PENDING_FINAL_APPROVAL', 'PARTIAL', 'Premium client, very specific about design.', NULL, 0, NULL, NULL, NULL),
  (5, 'DOM-PROJ-0005', NULL, 3, 8, 'Mehta Law Firm', 'Mehta & Associates', '9876543223', 'contact@mehtalaw.com', 'https://g.co/mehtalaw', NULL, 'Law firm website with practice areas, team profiles, case results and consultation booking', 'Professional, trustworthy design, online consultation form, live chat', 'Authoritative and professional. Navy blue and gold.', 28000, 14000, 8500, NULL, 'https://mehta-law-demo.netlify.app', 'REVISION_REQUIRED', 'PARTIAL', 'Client is a lawyer, very detail-oriented.', 'Contact form is not working. The consultation booking page loads slowly. Please fix both issues.', 1, NULL, NULL, NULL),
  (6, 'DOM-PROJ-0006', NULL, 2, 9, 'Sharma Bakery', 'Sharma Bake House', '9876543224', 'sharma@bakehouse.in', 'https://g.co/sharmabakery', 'https://instagram.com/sharmabakery', 'Bakery website with online ordering, delivery zones, custom cake builder', 'Warm cozy design, WhatsApp ordering, photo gallery, Google Maps integration', 'Homely and inviting. Brown, cream, and warm red palette.', 18000, 18000, 5500, 2500, 'https://sharma-bakehouse.com', 'COMPLETED', 'PAID', 'Full payment received before delivery.', NULL, 0, '2026-09-01 10:00:00+00', 1, '2026-09-01 10:00:00+00')
ON CONFLICT (id) DO NOTHING;

-- Link lead 6 with project 1
UPDATE leads SET project_id = 1 WHERE id = 6;

-- 4.5 LEAD FOLLOW-UPS (9 columns)
INSERT INTO lead_followups (id, lead_id, created_by, followup_date, followup_time, reason, client_position, notes, status) VALUES
  (1, 3, 2, '2026-10-25', '10:00', 'Client asked to call after Diwali', '90% interested, evaluating budget', 'Discuss final requirements and pricing', 'PENDING')
ON CONFLICT (id) DO NOTHING;

-- 4.6 MANAGER ESCALATIONS (9 columns)
INSERT INTO manager_escalations (id, lead_id, salesperson_id, manager_id, quoted_price, requirements, reason, salesperson_notes, status) VALUES
  (1, 5, 3, 5, 85000, 'Car dealership website with full inventory management system, EMI calculator, and CRM integration', 'High-value client. Discussed pricing but client wants to speak with senior management before committing.', 'Client is very serious. Price can be negotiated. Strongly recommend manager to close this.', 'PENDING_MANAGER')
ON CONFLICT (id) DO NOTHING;

-- 4.7 PROJECT STATUS HISTORY (4 columns)
INSERT INTO project_status_history (project_id, old_status, new_status, changed_by) VALUES
  (2, NULL, 'PENDING_ADMIN_APPROVAL', 1),
  (2, 'PENDING_ADMIN_APPROVAL', 'AVAILABLE_FOR_DEVELOPER', 1),
  (3, NULL, 'PENDING_ADMIN_APPROVAL', 1),
  (3, 'PENDING_ADMIN_APPROVAL', 'AVAILABLE_FOR_DEVELOPER', 1),
  (3, 'AVAILABLE_FOR_DEVELOPER', 'ASSIGNED', 1),
  (3, 'ASSIGNED', 'IN_DEVELOPMENT', 1),
  (4, NULL, 'PENDING_ADMIN_APPROVAL', 1),
  (4, 'PENDING_ADMIN_APPROVAL', 'AVAILABLE_FOR_DEVELOPER', 1),
  (4, 'AVAILABLE_FOR_DEVELOPER', 'ASSIGNED', 1),
  (4, 'ASSIGNED', 'IN_DEVELOPMENT', 1),
  (4, 'IN_DEVELOPMENT', 'SUBMITTED', 1),
  (4, 'SUBMITTED', 'PENDING_FINAL_APPROVAL', 1),
  (5, NULL, 'PENDING_ADMIN_APPROVAL', 1),
  (5, 'PENDING_ADMIN_APPROVAL', 'AVAILABLE_FOR_DEVELOPER', 1),
  (5, 'AVAILABLE_FOR_DEVELOPER', 'ASSIGNED', 1),
  (5, 'ASSIGNED', 'IN_DEVELOPMENT', 1),
  (5, 'IN_DEVELOPMENT', 'SUBMITTED', 1),
  (5, 'SUBMITTED', 'PENDING_FINAL_APPROVAL', 1),
  (5, 'PENDING_FINAL_APPROVAL', 'REVISION_REQUIRED', 1),
  (6, NULL, 'PENDING_ADMIN_APPROVAL', 1),
  (6, 'PENDING_ADMIN_APPROVAL', 'AVAILABLE_FOR_DEVELOPER', 1),
  (6, 'AVAILABLE_FOR_DEVELOPER', 'ASSIGNED', 1),
  (6, 'ASSIGNED', 'IN_DEVELOPMENT', 1),
  (6, 'IN_DEVELOPMENT', 'SUBMITTED', 1),
  (6, 'SUBMITTED', 'PENDING_FINAL_APPROVAL', 1),
  (6, 'PENDING_FINAL_APPROVAL', 'COMPLETED', 1);

-- 4.8 WALLET TRANSACTIONS (11 columns)
INSERT INTO wallet_transactions (
  id, transaction_id, wallet_id, user_id, project_id,
  type, amount, direction, description, status, created_by
) VALUES
  (1, 'TXN-000001', 9, 9, 6, 'DEVELOPER_EARNING', 5500, 'CREDIT', 'Project completion payout - DOM-PROJ-0006 (Sharma Bake House)', 'COMPLETED', 1),
  (2, 'TXN-000002', 2, 2, 6, 'SALES_COMMISSION', 2500, 'CREDIT', 'Sales commission - DOM-PROJ-0006 (Sharma Bake House)', 'COMPLETED', 1)
ON CONFLICT (id) DO NOTHING;

-- 4.9 PROJECT REVISION (6 columns)
INSERT INTO project_revisions (id, project_id, revision_number, rejection_reason, rejected_by, status) VALUES
  (1, 5, 1, 'Contact form is not working. The consultation booking page loads slowly. Please fix both issues.', 1, 'PENDING')
ON CONFLICT (id) DO NOTHING;

-- 4.10 PROJECT MESSAGES (3 columns)
INSERT INTO project_messages (project_id, sender_id, message) VALUES
  (3, 6, 'Hi, I have reviewed the requirements. Does the client want a dark theme by default or a toggle?'),
  (3, 2, 'Client prefers dark mode by default, but the toggle is a great idea! Please include it.'),
  (3, 6, 'Understood. Also, does the client want a blog with CMS or just static pages?'),
  (3, 2, 'Client wants a simple blog they can update themselves. CMS would be perfect.'),
  (3, 6, 'Got it. I will set up a headless CMS. Expected delivery: 2 weeks.');

-- 4.11 NOTIFICATIONS (7 columns)
INSERT INTO notifications (user_id, title, message, type, entity_type, entity_id, link) VALUES
  (6, 'New Project Available', 'A new project (Akhil General Stores) is available for developers.', 'ACTION_REQUIRED', 'project', 2, '/developer/projects'),
  (7, 'New Project Available', 'A new project (Akhil General Stores) is available for developers.', 'ACTION_REQUIRED', 'project', 2, '/developer/projects'),
  (1, 'Project Submitted for Approval', 'Nisha Fashion House website has been submitted by Sneha Reddy for final approval.', 'ACTION_REQUIRED', 'project', 4, '/admin/projects'),
  (8, 'Revision Requested', 'Admin has requested revisions on the Mehta Law Firm project.', 'WARNING', 'project', 5, '/developer/my-project'),
  (1, 'Project Pending Review', 'Iyer Catering project is pending your approval.', 'ACTION_REQUIRED', 'project', 1, '/admin/projects'),
  (2, 'Follow-up Due', 'Follow-up with Ramesh Pillai (Pillai Real Estate) is scheduled for 25 October.', 'INFO', 'lead', 3, '/sales/followups');

-- 4.12 LEAD ACTIVITIES (4 columns)
INSERT INTO lead_activities (lead_id, user_id, activity_type, description) VALUES
  (3, 2, 'CONTACTED', 'Called client. Client interested but asked to call after Diwali.'),
  (3, 2, 'FOLLOW_UP_CREATED', 'Follow-up scheduled for October 25, 2026.'),
  (4, 3, 'CONTACTED', 'Spoke with Kavitha Rao. Very interested. Wants appointment booking system.'),
  (5, 3, 'ESCALATED_TO_MANAGER', 'Lead escalated to manager for high-value client negotiation.'),
  (6, 2, 'CONVERTED', 'Lead converted. Project DOM-PROJ-0001 created. Advance ₹8000 collected.');

-- 4.13 SETTINGS (3 columns)
INSERT INTO settings (key, value, description) VALUES
  ('advance_mandatory', 'false', 'Whether advance payment is mandatory before project conversion'),
  ('company_name', 'Dominova', 'Company display name'),
  ('currency_symbol', '₹', 'Currency symbol to display')
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- 5. RE-SYNCHRONIZE IDENTITY SEQUENCES
-- ============================================================
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('wallets', 'id'), COALESCE((SELECT MAX(id) FROM wallets), 1));
SELECT setval(pg_get_serial_sequence('leads', 'id'), COALESCE((SELECT MAX(id) FROM leads), 1));
SELECT setval(pg_get_serial_sequence('projects', 'id'), COALESCE((SELECT MAX(id) FROM projects), 1));
SELECT setval(pg_get_serial_sequence('lead_followups', 'id'), COALESCE((SELECT MAX(id) FROM lead_followups), 1));
SELECT setval(pg_get_serial_sequence('manager_escalations', 'id'), COALESCE((SELECT MAX(id) FROM manager_escalations), 1));
SELECT setval(pg_get_serial_sequence('project_status_history', 'id'), COALESCE((SELECT MAX(id) FROM project_status_history), 1));
SELECT setval(pg_get_serial_sequence('project_messages', 'id'), COALESCE((SELECT MAX(id) FROM project_messages), 1));
SELECT setval(pg_get_serial_sequence('project_files', 'id'), COALESCE((SELECT MAX(id) FROM project_files), 1));
SELECT setval(pg_get_serial_sequence('project_revisions', 'id'), COALESCE((SELECT MAX(id) FROM project_revisions), 1));
SELECT setval(pg_get_serial_sequence('wallet_transactions', 'id'), COALESCE((SELECT MAX(id) FROM wallet_transactions), 1));
SELECT setval(pg_get_serial_sequence('withdrawals', 'id'), COALESCE((SELECT MAX(id) FROM withdrawals), 1));
SELECT setval(pg_get_serial_sequence('notifications', 'id'), COALESCE((SELECT MAX(id) FROM notifications), 1));
SELECT setval(pg_get_serial_sequence('audit_logs', 'id'), COALESCE((SELECT MAX(id) FROM audit_logs), 1));
SELECT setval(pg_get_serial_sequence('lead_activities', 'id'), COALESCE((SELECT MAX(id) FROM lead_activities), 1));
SELECT setval(pg_get_serial_sequence('settings', 'id'), COALESCE((SELECT MAX(id) FROM settings), 1));
